#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file using a while loop with IFS.

while IFS=':' read -r user passcode uid gid gecos home shell; do
  echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $gecos"
done < "/etc/passwd"
