#!/usr/bin/env bash
# Script to print "Best School" 10 times, "bad luck" on the 4th time, and "good luck" on the 8th time

message="Best School"
bad_luck="bad luck"
good_luck="good luck"
counter="0"
while [ $counter -lt 10 ]; do
	if [ $counter -eq 3 ]; then
		echo "$bad_luck"
	elif [ $counter -eq 7 ]; then
		echo "$good_luck"
	else
		echo "$message"
	fi
	((counter++))
done
