#!/usr/bin/env bash
# This script lists:
# The files and directories in the current directory
# In a list format
# Only showing the part of each name after the first dash

items=$(ls)
for item in $items; do
	echo "$item" | cut -d '-' -f 2
done
